-- | Module      : Gauge
--   Part VII (Synthesis), Parts III + VI face: schemes/quotient stacks and
--   gauge redundancy.
--
--   A finite permutation-group model of a group action @G @<@ X@ and the
--   quotient stack @[X/G]@.  The isotropy keystone of the Closure Theorem
--   (synthesis eq. mf7)
--
--     Aut_{[X/G]}(x)  ~=  Stab_G(x)
--
--   is realized here /twice, by two independent code paths/, and checked for
--   agreement:
--
--     * 'stabilizer' filters group elements by the fixed-point predicate
--       @g . x = x@ (the algebro-geometric / descent view, PIII/T2, PVI/T1);
--     * 'autGroupoid' extracts the endomorphisms @Hom(x,x)@ of the /action
--       groupoid/ @X // G@ (the type-theoretic view, PV/T4).
--
--   Their agreement ('isotropy') is the computational content of "one theorem,
--   four proofs" (synthesis Sec. "The isotropy theorem, four proofs").
module Gauge
  ( -- * Permutations
    Perm
  , isPerm
  , identityPerm
  , composePerm
  , invertPerm
  , applyPerm
    -- * Finite groups acting on {0..n-1}
    --
    -- The 'Group' constructor is intentionally hidden: groups may only be
    -- built by the validated smart builders below, so that every value of type
    -- 'Group' is a genuine, composition-closed group acting on @{0..n-1}@.
  , Group
  , groupDegree
  , groupElems
  , symmetricGroup
  , cyclicGroup
  , generatedGroup
  , isGroup
    -- * Orbits and stabilizers (PIII/T2, PVI/T1)
  , orbit
  , stabilizer
  , orbitStabilizer
  , stabilizerIsSubgroup
    -- * The action groupoid X // G and its automorphisms (PV/T4)
  , Groupoid(..)
  , actionGroupoid
  , autGroupoid
  , isotropy
  ) where

import Data.List (nub, permutations, sort)

-- | A permutation of @{0,..,n-1}@ given by its image list: @p !! i@ is the
--   image of @i@.
type Perm = [Int]

-- | Is @p@ a genuine permutation of @{0,..,n-1}@?  (Used to validate
--   generators before closing them into a group.)
isPerm :: Int -> Perm -> Bool
isPerm n p = length p == n && sort p == [0 .. n - 1]

-- | The identity permutation on @{0,..,n-1}@.
identityPerm :: Int -> Perm
identityPerm n = [0 .. max 0 n - 1]

-- | Group multiplication @(p . q)(i) = p(q(i))@ (function composition).
composePerm :: Perm -> Perm -> Perm
composePerm p q = [ p !! (q !! i) | i <- [0 .. length q - 1] ]

-- | The inverse permutation.
invertPerm :: Perm -> Perm
invertPerm p = [ j | i <- [0 .. n - 1], let j = lookupPre i ]
  where
    n :: Int
    n = length p

    lookupPre :: Int -> Int
    lookupPre i = go 0
      where
        go k
          | k >= n        = i               -- unreachable for a valid perm
          | p !! k == i   = k
          | otherwise     = go (k + 1)

-- | The action: @g@ sends the point @x@ to @g(x)@.  Total: an out-of-range
--   point is a fixed point (the safe default), so no partial index can crash.
applyPerm :: Perm -> Int -> Int
applyPerm p x
  | x >= 0 && x < length p = p !! x
  | otherwise              = x

-- | A finite group acting on @{0,..,degree-1}@, presented by the (finite,
--   composition-closed) list of its elements.
data Group = Group
  { groupDegree :: Int    -- ^ size of the underlying set @X = {0,..,degree-1}@
  , groupElems  :: [Perm] -- ^ the group elements, as permutations of @X@
  } deriving (Eq, Show)

-- | The full symmetric group @S_n@ (all permutations of @{0,..,n-1}@).  For
--   @n <= 0@ this is the trivial group on the empty set.
symmetricGroup :: Int -> Group
symmetricGroup n = Group (max 0 n) (permutations [0 .. max 0 n - 1])

-- | The cyclic group @C_n@ acting on @{0,..,n-1}@ by rotation.  For @n <= 0@
--   this is the trivial group (identity only), so the result is always a
--   genuine group.
cyclicGroup :: Int -> Group
cyclicGroup n
  | n <= 0    = Group 0 [identityPerm 0]
  | otherwise = Group n [ rot k | k <- [0 .. n - 1] ]
  where
    rot :: Int -> Perm
    rot k = [ (i + k) `mod` n | i <- [0 .. n - 1] ]

-- | The subgroup of @S_n@ generated by the given permutations, computed by
--   closing under composition (breadth-first) starting from the identity.
--   Generators that are not genuine permutations of @{0,..,n-1}@ are rejected
--   ('isPerm'), so the result is always a valid group.
generatedGroup :: Int -> [Perm] -> Group
generatedGroup n gens = Group nn (close [identityPerm nn])
  where
    nn :: Int
    nn = max 0 n

    valid :: [Perm]
    valid = filter (isPerm nn) gens

    close :: [Perm] -> [Perm]
    close known =
      let grown = nub (known ++ [ composePerm g h | g <- valid, h <- known ])
      in if length grown == length known then sort known else close grown

-- | Full validity predicate: every element is a genuine permutation of
--   @{0,..,degree-1}@, the elements are distinct, the identity is present, and
--   the set is closed under composition.  (Used as an invariant check, not for
--   control flow.)
isGroup :: Group -> Bool
isGroup g =
     all (isPerm (groupDegree g)) es
  && length (nub es) == length es
  && identityPerm (groupDegree g) `elem` es
  && and [ composePerm a b `elem` es | a <- es, b <- es ]
  where
    es :: [Perm]
    es = groupElems g

-- | The orbit @G . x = { g(x) : g in G }@.
orbit :: Group -> Int -> [Int]
orbit g x = nub [ applyPerm p x | p <- groupElems g ]

-- | The stabilizer @Stab_G(x) = { g in G : g(x) = x }@ (synthesis PIII/T2,
--   PVI/T1): the algebro-geometric / descent computation of isotropy.
stabilizer :: Group -> Int -> [Perm]
stabilizer g x = [ p | p <- groupElems g, applyPerm p x == x ]

-- | Orbit-stabilizer: @|orbit| * |Stab| == |G|@.
orbitStabilizer :: Group -> Int -> Bool
orbitStabilizer g x = length (orbit g x) * length (stabilizer g x) == length (groupElems g)

-- | The stabilizer is a subgroup: it contains the identity and is closed under
--   both composition and inversion.
stabilizerIsSubgroup :: Group -> Int -> Bool
stabilizerIsSubgroup g x =
     identityPerm (groupDegree g) `elem` st
  && and [ composePerm a b `elem` st | a <- st, b <- st ]
  && and [ invertPerm a       `elem` st | a <- st ]
  where
    st :: [Perm]
    st = stabilizer g x

-- | The action groupoid @X // G@: objects are the points of @X@; a morphism
--   @x -> y@ is a group element @g@ with @g(x) = y@ (synthesis PV/T4).
data Groupoid = Groupoid
  { objects   :: [Int]
  , morphisms :: [(Int, Perm, Int)] -- ^ @(source, arrow, target)@
  }

-- | Build the action groupoid of a group action.
actionGroupoid :: Group -> Groupoid
actionGroupoid g = Groupoid
  { objects   = [0 .. groupDegree g - 1]
  , morphisms = [ (x, p, applyPerm p x) | x <- [0 .. groupDegree g - 1], p <- groupElems g ]
  }

-- | @Aut_{X//G}(x) = Hom(x,x)@: the automorphisms of @x@ in the action
--   groupoid, extracted from the morphism set.  This is a /different/ code
--   path from 'stabilizer'.
autGroupoid :: Groupoid -> Int -> [Perm]
autGroupoid gpd x = [ p | (s, p, t) <- morphisms gpd, s == x, t == x ]

-- | The isotropy keystone (synthesis eq. mf7): the groupoid automorphism group
--   and the stabilizer subgroup coincide as sets.  Computed by comparing the
--   two independent constructions above.
isotropy :: Group -> Int -> Bool
isotropy g x = sort (autGroupoid (actionGroupoid g) x) == sort (stabilizer g x)
