-- |
-- Module      : Goncharov
-- Description : The Goncharov Lie coalgebra of a field, concretely on the
--               polylogarithmic generators, with the dilogarithm example.
--
-- Models the weight-graded Goncharov Lie coalgebra L_G(F) generated by
-- (motivic) polylogarithm symbols, and the discontinuity/cut computation of
-- Proposition (Discontinuity computes the first coaction slot).
module Goncharov
  ( KVar(..)
  , dilogSymbol
  , dilogCobracket
  , discAcross
  , weightOnePrimitives
  ) where

import Coalgebra

-- | The two weight-one generators for the dilogarithm's symbol alphabet:
-- @x@ (giving @log x@) and @1-x@ (giving @log(1-x)@).
data KVar = X | OneMinusX deriving (Eq, Ord)

instance Show KVar where
  show X          = "x"
  show OneMinusX  = "(1-x)"

-- | The symbol of the dilogarithm: @S(Li_2(x)) = -(1-x) (x) x@.
-- We record the word @(1-x) x@; the leading sign is tracked separately.
dilogSymbol :: Word' KVar
dilogSymbol = Word' [OneMinusX, X]

-- | The cobracket of the (motivic) dilogarithm:
--   @delta Li_2^m(x) = log(1-x) /\ log(x)@.
-- Returned as the signed antisymmetrization of the reduced coproduct.
dilogCobracket :: [(Word' KVar, Word' KVar, Rational)]
dilogCobracket = cobracket dilogSymbol

-- | Discontinuity across the branch point where the weight-one primitive
-- @s@ vanishes: pick the first-slot factors of the reduced coproduct whose
-- second slot is exactly the single letter @s@ (Proposition: Discontinuity
-- computes the first coaction slot).  Physically this is
-- @Disc_s A = 2 pi i * sum per(A_{i,1})@ over those terms.
discAcross :: Eq g => g -> Word' g -> [Word' g]
discAcross s w = [ a | (a, Word' [b]) <- reducedCoproduct w, b == s ]

-- | The weight-one primitives of the alphabet: they are exactly the
-- single-letter words, all primitive (cobracket vanishes).  This is the
-- @P_1 = F^x (x) Q@ statement of the generation theorem, at the level of
-- the model.
weightOnePrimitives :: [Word' KVar]
weightOnePrimitives = [ Word' [g] | g <- [X, OneMinusX] ]
